from debian:10.7

ENV GOPATH /tmp

ADD install_curl.sh install_curl.sh
ADD install_cmake.sh install_cmake.sh

RUN apt update && apt install -y g++ git wget python python3 python-numpy python3-numpy python-pip python3-pip \
zlib1g-dev python3-all-dev python-all-dev python-stdeb python3-stdeb

RUN pip  --no-cache-dir install cython && pip3 --no-cache-dir install cython

RUN ./install_curl.sh /curl &&  ./install_cmake.sh

ADD install_libfabric.sh install_libfabric.sh
RUN ./install_libfabric.sh

ARG OS
ENV OS=${OS}
ADD build.sh /bin/build.sh