{
 "title": "ASAP::O",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Shares",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Database",
     "measurement": "statistics",
     "query": "SELECT \"db_share\" FROM \"statistics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "db_share" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Disk",
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "disk_share" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Network",
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "network_share" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "data_volume" ], "type": "field" },
       {
        "params": [
         " / elapsed_ms/1024/1024/1024*1000*8"
        ],
        "type": "math"
       }
      ]
     ]
    },
    {
     "alias": "Database",
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "db_share" ], "type": "field" },
       {
        "params": [
         " *data_volume/ elapsed_ms/1024/1024/1024*1000*8"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Receiver",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RequestsRate",
     "query": "SELECT \"n_requests\" / elapsed_ms*1000 FROM \"statistics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "n_requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Broker",
     "measurement": "RequestsRate",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}