#!/usr/bin/env bash

if [ ! -f  /var/nomad/token ] && [ "${ACL_ENABLED}" = "true" ]; then
	nomad acl bootstrap > /var/nomad/bootstrap && \
	cat /var/nomad/bootstrap | grep Secret | awk '{print $4}' > /var/nomad/token && \
	cp /var/nomad/token $NOMAD_ALLOC_DIR/nomad_token
fi

if [ -f /var/run/asapo/user_vars.tfvars ]; then
  USER_VAR_FILE="-var-file=/var/run/asapo/user_vars.tfvars"
fi

cd /var/run/asapo && terraform apply -auto-approve $USER_VAR_FILE "$@"

if [ "${ACL_ENABLED}" = "true" ]; then
	cat /var/nomad/token
fi
