#!/usr/bin/env bash

#export NOMAD_TOKEN=`cat /var/nomad/token `

if [ -f /var/asapo/user_vars.tfvars ]; then
  USER_VAR_FILE="-var-file=/var/asapo/user_vars.tfvars"
fi

cd /var/asapo && terraform destroy -auto-approve $USER_VAR_FILE "$@"
