{
 "title": "Cluster Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "task",
    "query": "show tag values with key = task"
   }
  ]
 },
 "panels": [
  { "title": "$task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "task" },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "cpu_total_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " /mean(memory_allocated) * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "Log Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "logs",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "limit": "100",
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "$task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "cpu_total_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " /mean(memory_allocated) * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "Log Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "logs",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "limit": "100",
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "$task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "cpu_total_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " /mean(memory_allocated) * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "Log Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "logs",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "limit": "100",
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "$task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "cpu_total_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " /mean(memory_allocated) * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "Log Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "logs",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "limit": "100",
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "$task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 25 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "cpu_total_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 25 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " /mean(memory_allocated) * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "Log Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "logs",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "limit": "100",
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "$task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 31 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "cpu_total_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " /mean(memory_allocated) * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=~", "value": "/^$task$/" }
     ]
    }
   ]
  },
  {
   "title": "Log Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "logs",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "limit": "100",
     "measurement": "/^.*$task$/",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Nomad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Log Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "asapo.nomad",
     "select": [
      [
       { "params": [ "log" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "limit": "100",
     "measurement": "asapo.nomad",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}