package server

import (
	"asapo_common/utils"
)

var listRoutes = utils.Routes{
	utils.Route{
		"GetNext",
		"Get",
		"/database/{dbname}/{datasource}/{substream}/{groupid}/next",
		routeGetNext,
	},
	utils.Route{
		"GetSize",
		"Get",
		"/database/{dbname}/{datasource}/{substream}/size",
		routeGetSize,
	},
	utils.Route{
		"GetSubstreams",
		"Get",
		"/database/{dbname}/{datasource}/{substream}/substreams",
		routeGetSubstreams,
	},
	utils.Route{
		"GetLast",
		"Get",
		"/database/{dbname}/{datasource}/{substream}/0/last",
		routeGetLast,
	},
	utils.Route{
		"GetLastAck",
		"Get",
		"/database/{dbname}/{datasource}/{substream}/{groupid}/lastack",
		routeGetLastAck,
	},
	utils.Route{
		"GetNacks",
		"Get",
		"/database/{dbname}/{datasource}/{substream}/{groupid}/nacks",
		routeGetNacks,
	},
	utils.Route{
		"GetID",
		"Get",
		"/database/{dbname}/{datasource}/{substream}/0/{id}",
		routeGetByID,
	},
	utils.Route{
		"GetMeta",
		"Get",
		"/database/{dbname}/{datasource}/{substream}/0/meta/{id}",
		routeGetMeta,
	},
	utils.Route{
		"CreateGroup",
		"Post",
		"/creategroup",
		routeCreateGroupID,
	},
	utils.Route{
		"QueryImages",
		"Post",
		"/database/{dbname}/{datasource}/{substream}/0/queryimages",
		routeQueryImages,
	},
	utils.Route{
		"ResetConter",
		"Post",
		"/database/{dbname}/{datasource}/{substream}/{groupid}/resetcounter",
		routeResetCounter,
	},
	utils.Route{
		"ImageOp",
		"Post",
		"/database/{dbname}/{datasource}/{substream}/{groupid}/{id}",
		routeImageOp,
	},
	utils.Route{
		"Health",
		"Get",
		"/health",
		routeGetHealth,
	},
}
