apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizer-deployment
  labels:
    app: authorizer
spec:
  replicas: {{ .Values.authorizer.replicaCount }}
  selector:
    matchLabels:
      app: authorizer
  template:
    metadata:
      labels:
        app: authorizer
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/authorizer-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/auth-secret.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: all-in-one
          projected:
            sources:
              - configMap:
                  name: authorizer-config
              - secret:
                  name: auth-secret
        - name: shared-volume-offline
          persistentVolumeClaim:
            claimName: asapo-offline-pv
        - name: shared-volume-online
          persistentVolumeClaim:
            claimName: asapo-online-pv
      containers:
        - name: authorizer
          image: "yakser/asapo-authorizer-dev:{{ .Values.common.asapoVersionTag }}"
          command: ["/asapo-authorizer"]
          args: ["-config", "/etc/authorizer/authorizer.json"]
          ports:
            - containerPort: 5007
          volumeMounts:
            - mountPath: "/etc/authorizer"
              name: all-in-one
            - mountPath: {{ .Values.common.offlineDir }}
              name: shared-volume-offline
            - mountPath: {{ .Values.common.onlineDir }}
              name: shared-volume-online


