apiVersion: apps/v1
kind: Deployment
metadata:
  name: asapo-authorizer
  labels:
    app: asapo-authorizer
spec:
  replicas: {{ .Values.ownServices.authorizer.replicaCount }}
  selector:
    matchLabels:
      app: asapo-authorizer
  template:
    metadata:
      labels:
        app: asapo-authorizer
      annotations:
        checksum/config: {{ .Files.Get "configs/asapo-authorizer.json" | sha256sum  }}
        checksum/secret: {{ include (print $.Template.BasePath "/auth-secret.yaml") . | sha256sum }}
        checksum/secret-admin: {{ include (print $.Template.BasePath "/auth-secret-admin.yaml") . | sha256sum }}
        checksum/fluentd-config: {{ .Files.Get "configs/asapo-fluentd.conf" | sha256sum  }}
    spec:
      volumes:
        - name: all-in-one
          projected:
            sources:
              - configMap:
                  name: asapo-authorizer-config
              - secret:
                  name: auth-secret
              - secret:
                  name: auth-secret-admin
        - name: shared-volume-offline
          persistentVolumeClaim:
            claimName: asapo-offline-pv
        - name: shared-volume-online
          persistentVolumeClaim:
            claimName: asapo-online-pv
        {{- include "asapo.fluentd.volumes" .Values.ownServices.authorizer | indent 8 }}
      containers:
        - name: asapo-authorizer
          image: "yakser/asapo-authorizer-dev:{{ .Values.common.asapoVersionTag }}"
          command: ["/asapo-authorizer"]
          args: ["-config", "/etc/authorizer/asapo-authorizer.json"]
          ports:
            - containerPort: {{ .Values.ownServices.authorizer.port }}
          volumeMounts:
            - mountPath: "/etc/authorizer"
              name: all-in-one
            - mountPath: {{ .Values.common.offlineDir }}
              name: shared-volume-offline
            - mountPath: {{ .Values.common.onlineDir }}
              name: shared-volume-online
      {{- include "asapo.fluentd.container" . | indent 8 }}