apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizer-deployment
  labels:
    app: authorizer
spec:
  replicas: {{ .Values.authorizer.replicaCount }}
  selector:
    matchLabels:
      app: authorizer
  template:
    metadata:
      labels:
        app: authorizer
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/authorizer-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/auth-secret.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: all-in-one
          projected:
            sources:
              - configMap:
                  name: authorizer-config
              - secret:
                  name: auth-secret
      containers:
        - name: authorizer
          image: "yakser/asapo-authorizer-dev:develop.19.09-210-gd2bfa78"
          command: ["/asapo-authorizer"]
          args: ["-config", "/etc/authorizer/authorizer.json"]
          ports:
            - containerPort: 5007
          volumeMounts:
            - name: all-in-one
              mountPath: "/etc/authorizer"
