apiVersion: apps/v1
kind: Deployment
metadata:
  name: asapo-broker
  labels:
    app: asapo-broker
spec:
  replicas: {{ .Values.ownServices.broker.replicaCount }}
  selector:
    matchLabels:
      app: asapo-broker
  template:
    metadata:
      labels:
        app: asapo-broker
      annotations:
        checksum/config: {{ .Files.Get "configs/asapo-broker.json" | sha256sum  }}
        checksum/fluentd-config: {{ .Files.Get "configs/asapo-fluentd.conf" | sha256sum  }}
        checksum/secret: {{ include (print $.Template.BasePath "/auth-secret.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: all-in-one
          projected:
            sources:
              - configMap:
                  name: asapo-broker-config
              - secret:
                  name: auth-secret
        {{- include "asapo.fluentd.volumes" .Values.ownServices.broker | indent 8 }}
      initContainers:
        - name: wait-databases
          image: busybox:1.28
          command: ['sh', '-c', "echo initializing;until wget -T 2 asapo-influxdb:8086/ping; do echo waiting for influxdb; sleep 2; done"]
      containers:
        - name: asapo-broker
          image: "yakser/asapo-broker-dev:{{ .Values.common.asapoVersionTag }}"
          command: ["/asapo-broker"]
          args: ["-config", "/etc/broker/asapo-broker.json"]
          ports:
            - containerPort: {{ .Values.ownServices.broker.port }}
          volumeMounts:
            - mountPath: "/etc/broker"
              name: all-in-one
        {{- include "asapo.fluentd.container" . | indent 8 }}
