{{- range .Values.ownServices }}
  {{ $data := dict "Release" $.Release "Chart" $.Chart "Template" $.Template "Values" $.Values "Files" $.Files "service" . }}
    {{- template "asapo.configmap-fromfile" $data }}
---
{{- end }}
