apiVersion: apps/v1
kind: Deployment
metadata:
  name: asapo-receiver
  labels:
    app: asapo-receiver
spec:
  replicas: {{ .Values.ownServices.receiver.replicaCount }}
  selector:
    matchLabels:
      app: asapo-receiver
  template:
    metadata:
      labels:
        app: asapo-receiver
      annotations:
        checksum/config: {{ .Files.Get "configs/asapo-receiver.json" | sha256sum  }}
        checksum/fluentd-config: {{ .Files.Get "configs/asapo-fluentd.conf" | sha256sum  }}
    spec:
      volumes:
        - name: asapo-receiver-config
          configMap:
            name: asapo-receiver-config
        - name: shared-volume-offline
          persistentVolumeClaim:
            claimName: asapo-offline-pv
        - name: shared-volume-online
          persistentVolumeClaim:
            claimName: asapo-online-pv
        {{- include "asapo.fluentd.volumes" .Values.ownServices.receiver | indent 8 }}
      containers:
        - name: asapo-receiver
          image: "yakser/asapo-receiver-dev:{{ .Values.common.asapoVersionTag }}"
          command: ["/receiver"]
          args: ["/etc/receiver/asapo-receiver.json"]
          ports:
            - containerPort: {{ .Values.ownServices.receiver.port }}
              name: http
            - containerPort: {{ .Values.ownServices.receiver.dataServer.port }}
              name: http-ds
          volumeMounts:
            - mountPath: "/etc/receiver"
              name: asapo-receiver-config
            - mountPath: {{ .Values.common.offlineDir }}
              name: shared-volume-offline
            - mountPath: {{ .Values.common.onlineDir }}
              name: shared-volume-online
      {{- include "asapo.fluentd.container" . | indent 8 }}