from centos:8.3.2011

RUN yum update -y
RUN yum -y groupinstall "Development Tools"
RUN yum config-manager --set-enabled powertools
RUN yum -y install wget rpm-build zlib-devel python3-devel python3-numpy
RUN yum -y install glibc-static libstdc++-static
RUN pip3 install cython
RUN ln -s /usr/bin/python3 /usr/bin/python

ADD install_cmake.sh install_cmake.sh
RUN ./install_cmake.sh

ADD install_curl.sh install_curl.sh
RUN ./install_curl.sh /curl

ADD install_libfabric.sh install_libfabric.sh
RUN ./install_libfabric.sh

ADD install_grpc.sh install_grpc.sh
RUN ./install_grpc.sh

RUN yum -y install libcurl-devel

ENV GOPATH /tmp
ENV OS el8
ADD build.sh /bin/build.sh
