{
 "title": "Asapo Client Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "SHOW TAG VALUES WITH KEY = \"job\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "job", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Telegraf",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=", "value": "telegraf" }
     ]
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=", "value": "grafana" }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "query": "SELECT mean(\"memory_rss\") /mean([[memory_allocated]]) * 100 FROM \"nomad_client_allocs\" WHERE (\"job\" = 'monitoring') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "/mean(\"memory_allocated\") * 100"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "job", "operator": "=", "value": "monitoring" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nomad_client_allocs",
     "select": [
      [
       { "params": [ "cpu_total_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "job", "operator": "=", "value": "monitoring" }
     ]
    }
   ]
  }
 ]
}